name: HardcoreCoop
version: 1.0
author: Poenzel
main: be.poenzel.hardcorecoop.HardcoreCoop
api-version: 1.21.11
commands:
  hc:
    description: Main command for the HardcoreCoop
    permission: hc.use